name: "SX127x LoRa Component"
version: "1.0.0"
esphome:
  name: sx127x
  friendly_name: "SX127x LoRa"
  includes:
    - sx127x.h

dependencies:
  - spi

configuration:
  cs_pin:
    type: gpio
    required: true
    description: "Chip Select (CS) pin for SPI communication"
  reset_pin:
    type: gpio
    required: true
    description: "Reset pin for LoRa module"
  dio0_pin:
    type: gpio
    required: true
    description: "DIO0 pin for interrupt handling"
  frequency:
    type: float
    required: true
    description: "LoRa frequency (e.g., 433MHz, 866MHz, 915MHz)"
  tx_power:
    type: int
    default: 20
    description: "Transmission power (2dB - 20dB)"
  sync_word:
    type: int
    default: 0x12
    description: "Sync word for LoRa communication"

codeowners:
  - "@Barbariyo"

documentation: "https://github.com/Barbariyo/esphome-lora-component"
